input_dirs:
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/histone_graph_calling/sm_test
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/histone_graph_calling/sm_test_2
log_dir: logs/slurm
vg_dir: /gpfs/gibbs/pi/gerstein/hc865/downloads/vg_old
