input_dirs:
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/adrenal_gland
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/ascending_aorta
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/body_of_pancreas
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/breast_epithelium
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/coronary_artery
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/esophagus_muscularis_mucosa
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/esophagus_squamous_epithelium
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/gastrocnemius_medialis
  - /gpfs/gibbs/pi/gerstein/hc865/downloads/H3K4me3_graph_calling/gastroesophageal_sphincter

log_dir: logs/slurm
filter_script: scripts/filter_gam.sh
gamtojson_script: scripts/gam_to_json.sh
gpc_env: /gpfs/gibbs/pi/gerstein/hc865/cvenv/
graph_dir: /gpfs/gibbs/pi/gerstein/hc865/downloads/vg_giraffe/vg_graphs_a
vg_path: /gpfs/gibbs/pi/gerstein/hc865/downloads/vg_old

chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY

genome_size: 3100000000
read_length: 101
